version: '3.3'
services:
  post_db:
    image: mongo:${SERVICE_POST_DB_VER}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
    container_name: my_post_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${SERVICE_UI_VER}
    ports:
      - ${FRONT_PORT}/tcp
    networks:
      - front_net
    container_name: my_ui_service
  post:
    build: ./post-py
    image: ${USERNAME}/post:${SERVICE_POST_VER}
    networks:
      - back_net
      - front_net
    container_name: my_post_service
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${SERVICE_COMMENT_VER}
    networks:
      - back_net
      - front_net
    container_name: my_comment_service

volumes:
  post_db:

networks:
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_BACK_SUBNET}
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_FRONT_SUBNET}
